### ISSUE TITLE
[FEATURE] Band Pass Filter Option?

### ISSUE THREAD

**Issue by Manthosdm** [Chowdhury-DSP/ChowMultiTool#20]
Hello there! I downloaded ChowMultiTool, and it's a great all-round tool for many, many, many applications. And it's so nice to have a Chow-quality plugin for that!

I mainly use it for setting up parallel filter sends. Like this! [https://www.youtube.com/watch?v=4hGBYs10ZAU&t=527s&pp=ygUPcGFyYWxsZWwgd29ycmFs](url)

All I've been lacking is a proper band pass. I mean, I can make it happen by combining a high pass and low pass... but then if I want to tune the frequency, I have to fine-tune two filters one after the other. 

Is there any possibility of implementing a bandpass?

Thanks for everything you do :)

**Comment by jatinchowdhury18** [comment]
Hello! Glad you're enjoying the plugin.

ChowMultiTool currently has a bandpass filter implemented as part of the SVF tool... I'm guessing that you're requesting the bandpass filter be added to the EQ tool as well? I'm wondering if there's a specific reason that the SVF implementation wouldn't work for your use case?

**Comment by Manthosdm** [comment]
I checked it, works fine for me! I didn't look at the SVF tool, I regarded it as a sound design module, not so much as a the surgical/clean kind of eq I would use for what I do. But it seems that it is 😓. Thanks for the reply!

**Comment by jatinchowdhury18** [comment]
Sure thing! Yeah, the SVF "plain" mode filters are very similar to the filters in the EQ, so it should be possible to do a lot of the same things.
