### ISSUE TITLE
[BUG] does not work on reaper 6.79, linux mint 20 64 bit.

### ISSUE THREAD

**Issue by TheGuyWhoo** [Chowdhury-DSP/ChowMultiTool#25]
Only the .lv2 scans successfully, and it says failed to load when I try to load it on to a track. The clap and vst3 completely fail to even scan.

**Comment by jatinchowdhury18** [comment]
Thanks for the bug report! I'm guessing the issue with the LV2 plugin is related to the fact that ChowMultiTool has multiple output busses. I know that LV2 sometimes has plugin/host compatibility issues with plugins that have more complex routing configurations although I don't know all the specifics.

The fact that the CLAP and VST3 plugins aren't scanning leads me to believe there may be a larger issue at play. Do you know if Reaper makes any logs during the plugin scanning process? If it's possible to obtain some more information about the scanning failures, that would be very helpful.

Unfortunately, I don't have a non-headless Linux setup available to me at the moment, but I'll see if I can work out a way to debug what's going on here.

One question: was the plugin installed from the .deb package provided with the latest release, or are you building from source?

**Comment by TheGuyWhoo** [comment]
Unfortunately I don't think reaper logs what fails during the scanning processing, it only has a list of the plugins that failed.

It does output this when I try to load the lv2:

swell: dlopen() failed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/lv2/ChowMultiTool.lv2/libChowMultiTool.so)

Yes, I installed it from .deb file.

**Comment by jatinchowdhury18** [comment]
Okay cool, that error message is very helpful. Basically, the plugin is expecting that the host system will have libc version 2.35 (or higher) available. This version of libc is standard for Ubuntu 22.04 (which is what our Linux build machine was running). Unfortunately, for Ubuntu 20.04 [libc version 2.31 is the standard](https://github.com/espressif/esptool/issues/843), and I would guess that's the case for Linux Mint 20 is as well.

Anyway, I'm trying downgrading the build machine to Ubuntu 20.04, and making some new builds. If you'd like to try the next [Nightly Builds](https://chowdsp.com/nightly.html#multitool) (probably ready in an half an hour or so) hopefully they should work on your system (in all the plugin formats).

**Comment by TheGuyWhoo** [comment]
That worked, thank you!
