### ISSUE TITLE
[FEATURE] Bandsplitter and Brickwall need frequency label

### ISSUE THREAD

**Issue by tapir** [Chowdhury-DSP/ChowMultiTool#30]
**Is your feature request related to a problem? Please describe.**
I can't see the frequency accurately when I'm working on band splitter or brickwall like in other tools

**Describe the solution you'd like**
Just like in other tools we can have small label that says "Freq: XXX"

**Comment by jatinchowdhury18** [comment]
Yeah, good idea!

I got the brickwall label working today. We're planning on making some other tweaks for the band-splitter, so I'll wait until those are done to do the same thing there.

<img width="1109" alt="Screen Shot 2023-11-12 at 9 19 50 PM" src="https://github.com/Chowdhury-DSP/ChowMultiTool/assets/13724188/4dc0534d-da7d-445a-90bd-b0109eebd6d5">

The latest updates will be in the next [Nightly Build](https://chowdsp.com/nightly.html#multitool) (probably up in the next few hours) in case you'd like to try it out.

**Comment by jatinchowdhury18** [comment]
Resolved with #34
